extends: substitution
message: "Avoid vague text in links like '%s' unless you can pair it with more descriptive text."
link: 'https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#links'
ignorecase: true
scope: raw
nonword: true
level: warning

swap:
# For the word 'here' in Markdown links
  '\[here\]\(.*?\)': 'here'

# For the word 'this' in Markdown links
  '\[this\]\(.*?\)': 'this'

# For the word 'page' in Markdown links
  '\[page\]\(.*?\)': 'page'

# For the phrase 'this page' in Markdown links
  '\[this page\]\(.*?\)': 'this page'

